language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t blazestudios23/docker-react -f Dockerfile.dev .
script:
  # - docker run blazestudios23/docker-react npm run test -- --coverage
  - docker run -e CI=true blazestudios23/docker-react npm run test
